import json
json_data_string ='''
{
  "PHONE": {
    "ID": 24793,
    "NAME": "Телефон",
    "TYPE_ID": 2,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "PHONE",
    "SORT": 2,
    "ENTREE_CONTACTS": 1,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "Y",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 2
    },
    "ENTREE_DEALS": 0,
    "TYPE_CODE": "PHONE",
    "~NAME": "Телефон",
    "ENUMS": {
      "12365": {
        "ID": 12365,
        "VALUE": "WORK",
        "~VALUE": "WORK",
        "SORT": 2,
        "code": null,
        "TOTAL": 0
      },
      "12367": {
        "ID": 12367,
        "VALUE": "PRIV",
        "~VALUE": "PRIV",
        "SORT": 4,
        "code": null,
        "TOTAL": 0
      },
      "12369": {
        "ID": 12369,
        "VALUE": "OTHER",
        "~VALUE": "OTHER",
        "SORT": 6,
        "code": null,
        "TOTAL": 0
      }
    }
  },
  "WEB": {
    "ID": 24797,
    "NAME": "Web",
    "TYPE_ID": 7,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "WEB",
    "SORT": 8,
    "ENTREE_CATALOG": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 3
    },
    "ENTREE_DEALS": 0,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 1,
    "ENTREE_CUSTOMERS": 0,
    "TYPE_CODE": "URL",
    "~NAME": "Web"
  },
  "ADDRESS": {
    "ID": 24799,
    "NAME": "Адрес",
    "TYPE_ID": 9,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "ADDRESS",
    "SORT": 10,
    "ENTREE_CATALOG": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 3
    },
    "ENTREE_DEALS": 0,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 1,
    "ENTREE_CUSTOMERS": 0,
    "TYPE_CODE": "TEXTAREA",
    "~NAME": "Адрес"
  },
  "UTM_CONTENT": {
    "ID": 24801,
    "NAME": "utm_content",
    "TYPE_ID": 21,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "UTM_CONTENT",
    "SORT": 503,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MUSORT": 516,
        "ENTREE_CONTACTS": 0,
        "ENTREE_COMPANY": 0,
        "ENTREE_CATALOG": 0,
        "ENTREE_CUSTOMERS": 0,
        "PREDEFINED": "Y",
        "MULTIPLE": "N",
        "DISABLED": 0,
        "ORIGIN": null,
        "CATALOG_ID": null,
        "SETTINGS": {
            "is_required": {},
            "is_deletable": true,
            "is_visible": null,
            "triggers": null,
            "vat_rates": {},
            "filter_type": null,
            "tracking_callback": "",
            "search_in": "",
            "currency": "",
            "chained_lists": null
        },
        "deleted_at": null,
        "ELEMENT_TYPES": {"0": 2},
        "ENTREE_DEALS": 1,
        "TYPE_CODE": "TRACKING_DATA",
        "~NAME": "gclientid"
    },
    "YCLID": {
        "ID": 24835,
        "NAME": "yclid",
        "TYPE_ID": 21,
        "ACCOUNT_ID": 32001522,
        "DESCRIPTION": null,
        "CODE": "YCLID",
        "SORT": 520,
        "ENTREE_CONTACTS": 0,
        "ENTREE_COMPANY": 0,
        "ENTREE_CATALOG": 0,
        "ENTREE_CUSTOMERS": 0,
        "PREDEFINED": "Y",
        "MULTIPLE": "N",
        "DISABLED": 0,
        "ORIGIN": null,
        "CATALOG_ID": null,
        "SETTINGS": {
            "is_required": {},
            "is_deletable": null,
            "is_visible": null,
            "triggers": null,
            "vat_rates": {},
            "filter_type": null,
            "tracking_callback": "",
            "search_in": "",
            "currency": "",
            "chained_lists": null
        },
        "deleted_at": null,
        "ELEMENT_TYPES": {"0": 2},
        "ENTREE_DEALS": 1,
        "TYPE_CODE": "TRACKING_DATA",
        "~NAME": "yclid"
    },
    "_YM_UID": {
        "ID": 24829,
        "NAME": "_ym_uid",
        "TYPE_ID": 21,
        "ACCOUNT_ID": 32001522,
        "DESCRIPTION": null,
        "CODE": "_YM_UID",
        "SORT": 517,
        "ENTREE_CONTACTS": 0,
        "ENTREE_COMPANY": 0,
        "ENTREE_CATALOG": 0,
        "ENTREE_CUSTOMERS": 0,
        "PREDEFINED": "Y",
        "MULTIPLE": "N",
        "DISABLED": 0,
        "ORIGIN": null,
        "CATALOG_ID": null,
        "SETTINGS": {
            "is_required": {},
            "is_deletable": null,
            "is_visible": null,
            "triggers": null,
            "vat_rates": {},
            "filter_type": null,
            "tracking_callback": "",
            "search_in": "",
            "currency": "",
            "chained_lists": null
        },
        "deleted_at": null,
        "ELEMENT_TYPES": {"0": 2},
        "ENTREE_DEALS": 1,
        "TYPE_CODE": "TRACKING_DATA",
        "~NAME": "_ym_uid"
    },
    "_YM_COUNTER": {
        "ID": 24831,
        "NAME": "_ym_counter",
        "TYPE_ID": 21,
        "ACCOUNT_ID": 32001522,
        "DESCRIPTION": null,
        "CODE": "_YM_COUNTER",
        "SORT": 518,
        "ENTREE_CONTACTS": 0,
        "ENTREE_COMPANY": 0,
        "ENTREE_CATALOG": 0,
        "ENTREE_CUSTOMERS": 0,
        "PREDEFINED": "Y",
        "MULTIPLE": "N",
        "DISABLED": 0,
        "ORIGIN": null,
        "CATALOG_ID": null,
        "SETTINGS": {
            "is_required": {},
            "is_deletable": true,
            "is_visible": true,
            "triggers": null,
            "vat_rates": {},
            "filter_type": null,
            "tracking_callback": "",
            "search_in": "",
            "currency": "",
            "chained_lists": null
        },
        "deleted_at": null,
        "ELEMENT_TYPES": {"0": 2},
        "ENTREE_DEALS": 1,
        "TYPE_CODE": "TRACKING_DATA",
        "~NAME": "_ym_counter"
    },
    "GCLID": {
        "ID": 24833,
        "NAME": "gclid",
        "TYPE_ID": 21,
        "ACCOUNT_ID": 32001522,
        "DESCRIPTION": null,
        "CODE": "GCLID",
        "SORT": 519,
        "ENTREE_CONTACTS": 0,
        "ENTREE_COMPANY": 0,
        "ENTREE_CATALOG": 0,
        "ENTREE_CUSTOMERS": 0,
        "PREDEFINED": "Y",
        "MULTIPLE": "N",
        "DISABLED": 0,
        "ORIGIN": null,
        "CATALOG_ID": null,
        "SETTLTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 2
    },
    "ENTREE_DEALS": 1,
    "TYPE_CODE": "TRACKING_DATA",
    "~NAME": "utm_content"
  },
  "POSITION": {
    "ID": 24791,
    "NAME": "Должность",
    "TYPE_ID": 1,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "POSITION",
    "SORT": 503,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 1
    },
    "ENTREE_DEALS": 0,
    "ENTREE_CONTACTS": 1,
    "TYPE_CODE": "TEXT",
    "~NAME": "Должность"
  },
  "UTM_MEDIUM": {
    "ID": 24803,
    "NAME": "utm_medium",
    "TYPE_ID": 21,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "UTM_MEDIUM",
    "SORT": 504,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 2
    },
    "ENTREE_DEALS": 1,
    "TYPE_CODE": "TRACKING_DATA",
    "~NAME": "utm_medium"
  },
  "UTM_CAMPAIGN": {
    "ID": 24805,
    "NAME": "utm_campaign",
    "TYPE_ID": 21,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "UTM_CAMPAIGN",
    "SORT": 505,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 2
    },
    "ENTREE_DEALS": 1,
    "TYPE_CODE": "TRACKING_DATA",
    "~NAME": "utm_campaign"
  },
  "UTM_SOURCE": {
    "ID": 24807,
    "NAME": "utm_source",
    "TYPE_ID": 21,
    "ACCOUNT_ID": 32001522,
    "DESCRIPTION": null,
    "CODE": "UTM_SOURCE",
    "SORT": 506,
    "ENTREE_CONTACTS": 0,
    "ENTREE_COMPANY": 0,
    "ENTREE_CATALOG": 0,
    "ENTREE_CUSTOMERS": 0,
    "PREDEFINED": "Y",
    "MULTIPLE": "N",
    "DISABLED": 0,
    "ORIGIN": null,
    "CATALOG_ID": null,
    "SETTINGS": {
      "is_required": {},
      "is_deletable": true,
      "is_visible": true,
      "triggers": null,
      "vat_rates": {},
      "filter_type": null,
      "tracking_callback": "",
      "search_in": "",
      "currency": "",
      "chained_lists": null
    },
    "deleted_at": null,
    "ELEMENT_TYPES": {
      "0": 2
    },
    "ENTREE_DEALS": 1,
        "TYPE_CODE": "TRACKING_DATA",
        "~NAME": "utm_source"
        "OPENSTAT_AD":{
        "ID":24821,
        "NAME":"openstat_ad",
        "TYPE_ID":21,
        "ACCOUNT_ID":32001522,
        "DESCRIPTION":null,
        "CODE":"OPENSTAT_AD",
        "SORT":513,
        "ENTREE_CONTACTS":0,
        "ENTREE_COMPANY":0,
        "ENTREE_CATALOG":0,
        "ENTREE_CUSTOMERS":0,
        "PREDEFINED":"Y",
        "MULTIPLE":"N",
        "DISABLED":0,
        "ORIGIN":null,
        "CATALOG_ID":null,
        "SETTINGS":{
            "is_required":{},
            "is_deletable":true,
            "is_visible":true,
            "triggers":null,
            "vat_rates":{},
            "filter_type":null,
            "tracking_callback":"",
            "search_in":"","currency":"",
            "chained_lists":null},
            "deleted_at":null,
            "ELEMENT_TYPES":{"0":2},
            "ENTREE_DEALS":1,
            "TYPE_CODE":"TRACKING_DATA",
            "~NAME":"openstat_ad"}
    "OPENSTAT_SOURCE":{
        "ID":24823,
        "NAME":"openstat_source",
        "TYPE_ID":21,
        "ACCOUNT_ID":32001522,
        "DESCRIPTION":null,
        "CODE":"OPENSTAT_SOURCE",
        "SORT":514,
        "ENTREE_CONTACTS":0,
        "ENTREE_COMPANY":0,
        "ENTREE_CATALOG":0,
        "ENTREE_CUSTOMERS":0,
        "PREDEFINED":"Y",
        "MULTIPLE":"N",
        "DISABLED":0,
        "ORIGIN":null,
        "CATALOG_ID":null,
        "SETTINGS":{
        "is_required":{},
        "is_deletable":true,
        "is_visible":true,
        "triggers":null,
        "vat_rates":{},
        "filter_type":null,
        "tracking_callback":"",
        "search_in":"",
        "currency":"",
        "chained_lists":null},
        "deleted_at":null,
        "ELEMENT_TYPES":{"0":2},
        "ENTREE_DEALS":1,
        "TYPE_CODE":"TRACKING_DATA",
        "~NAME":"openstat_source"}
    }
}
'''

try:
    data = json.loads(json_data_string)
    # Доступ к данным:
    print(data["OPENSTAT_AD"]["NAME"])  # Выведет: openstat_ad
    print(data["OPENSTAT_SOURCE"]["ID"]) # Выведет: 24823
    # и так далее...

except json.JSONDecodeError as e:
    print(f"Ошибка разбора JSON: {e}")
except KeyError as e:
    print(f"Ключ не найден: {e}")
except Exception as e:
    print(f"Произошла ошибка: {e}")
